### ISSUE TITLE
Option to hide cast option in player

### ISSUE THREAD

**Issue by pointydev** [FrankerFaceZ/FrankerFaceZ#1395]
**Is your feature request related to a problem? Please describe.**
I'd rather not cast watching the worst streams on Twitch to the living room TV.

**Describe the solution you'd like**
An option to hide the cast button in FrankerFaceZ for convenience.

**Describe alternatives you've considered**
Some simple CSS in Stylus:
```css
.player-controls__right-control-group :has(.tw-chromecast-button__icon) {
    display: none;
}
```

**Additional context**
![cast button](https://github.com/FrankerFaceZ/FrankerFaceZ/assets/22241432/ccb03606-6604-417d-b341-b604e57ff9e1)

Thanks,
pointy
