### ISSUE TITLE
Chat messages Separators not displaying 

### ISSUE THREAD

**Issue by ninox14** [FrankerFaceZ/FrankerFaceZ#1572]
**Describe the bug**
Chat message Separators are invisible cause of extra rule that overrides and makes them transparent in `ffz--managed-style--1`
Rule that overrides and makes separators transparent
```css 
.thread-message__message:last-child:nth-child(odd), .thread-message__timestamp:last-child:nth-child(odd), .thread-message__warning:last-child:nth-child(odd), .ffz--points-line:last-child:nth-child(odd), .chat-line__message:not(.chat-line--inline):last-child:nth-child(odd), .chat-line__moderation:last-child:nth-child(odd), .chat-line__status:last-child:nth-child(odd), .chat-line__raid:last-child:nth-child(odd), .user-notice-line:last-child:nth-child(odd) {
    border-bottom-color: rgba(0, 0, 0, 0) !important;
}
```

**To Reproduce**
1. Go to 'Chat>Appearance'
2. Click on 'Separators'
3. Select 'Any style of separator besides disabled'
4. See that they are not working  

**Expected behavior**
Separator lines visible between every chat message 

**Screenshots**
![image](https://github.com/user-attachments/assets/66b3ab83-b20b-48ad-9b43-e122bb618677)
![image](https://github.com/user-attachments/assets/071fef48-71fc-4632-b4b0-71324af86c7a)

**Environment (please complete the following information):**
 - OS: Windows 11
 - Browser chrome
 - Version 130.0.6723.70 (
 - Other Extensions: 
![image](https://i.imgur.com/qQDdtkp.png) 
![image](https://i.imgur.com/dxGjDSf.png) 
 Stylebot extension doesn't affect those rules at all it only used to change 2 background colors (follow list and description background) 

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**: 
https://logs.frankerfacez.com/60c51dd5-4575-48f5-ac58-04f3b1d6c8d8

**Additional context**
